name: Solidity docs

on:
  pull_request:
  push:
    branches:
      - releases/mainnet/solidity/**
  release:
    types:
      - "published"
  workflow_dispatch:

jobs:
  docs-detect-changes:
    runs-on: ubuntu-latest
    outputs:
      path-filter: ${{ steps.filter.outputs.path-filter }}
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'pull_request'
        id: filter
        with:
          filters: |
            path-filter:
              - './solidity/contracts/**'
              - './.github/workflows/contracts-docs.yml'

  # This job will be triggered for PRs which modify contracts. It will generate
  # the archive with contracts documentation in Markdown and attatch it to the
  # workflow run results. Link to the archive will be posted in a PR comment.
  # The job will also be run after manual triggering and after pushes to the
  # `releases/mainnet/solidity/**` branches.
  contracts-docs-publish-preview:
    name: Publish preview of contracts documentation
    needs: docs-detect-changes
    if: |
      needs.docs-detect-changes.outputs.path-filter == 'true'
        || github.event_name == 'push'
        || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: solidity/yarn.lock

      # Configure git to use HTTPS instead of SSH for GitHub repositories
      - name: Configure git for CI
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Remove unnecessary `//` comment used in the `@dev` section of `BitcoinTx` documentation
      - name: Preprocess BitcoinTx.sol
        run: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol

      - name: Build contracts
        run: yarn build

      - name: Generate documentation
        run: npx hardhat docgen

      - name: Create documentation archive
        run: |
          mkdir -p docs-archive
          if [ -d "generated-docs" ] && [ "$(ls -A generated-docs)" ]; then
            cp -r generated-docs/* docs-archive/
            tar -czf contracts-docs.tar.gz docs-archive/
          else
            echo "No documentation generated" > docs-archive/README.txt
            tar -czf contracts-docs.tar.gz docs-archive/
          fi

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts-documentation
          path: contracts-docs.tar.gz

  # This job will be triggered for releases which name starts with
  # `refs/tags/solidity/`. It will generate contracts documentation in
  # Markdown and sync it with a specific path of
  # `threshold-network/threshold` repository. If changes will be detected,
  # a PR updating the docs will be created in the destination repository. The
  # commit pushing the changes will be verified using GPG key.
  contracts-docs-publish:
    name: Publish contracts documentation
    needs: docs-detect-changes
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/solidity/')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: solidity/yarn.lock

      # Configure git to use HTTPS instead of SSH for GitHub repositories
      - name: Configure git for CI
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://github.com/".insteadOf "git@github.com:"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Remove unnecessary `//` comment used in the `@dev` section of `BitcoinTx` documentation
      - name: Preprocess BitcoinTx.sol
        run: sed -i ':a;N;$!ba;s_///\n//\n_///\n_g' ./contracts/bridge/BitcoinTx.sol

      - name: Build contracts
        run: yarn build

      - name: Generate documentation
        run: npx hardhat docgen

      - name: Publish documentation to threshold repository
        env:
          GITHUB_TOKEN: ${{ secrets.THRESHOLD_DOCS_GITHUB_TOKEN }}
        run: |
          # Clone the destination repository
          git clone https://github.com/threshold-network/threshold.git threshold-docs
          cd threshold-docs

          # Configure git user
          git config user.email "38324465+thesis-valkyrie@users.noreply.github.com"
          git config user.name "Valkyrie"

          # Copy documentation files
          rm -rf ./docs/app-development/tbtc-v2/tbtc-contracts-api/tbtc-v2-api
          mkdir -p ./docs/app-development/tbtc-v2/tbtc-contracts-api/tbtc-v2-api
          if [ -d "../generated-docs" ] && [ "$(ls -A ../generated-docs)" ]; then
            cp -r ../generated-docs/* ./docs/app-development/tbtc-v2/tbtc-contracts-api/tbtc-v2-api/
          else
            echo "No documentation generated" > ./docs/app-development/tbtc-v2/tbtc-contracts-api/tbtc-v2-api/README.txt
          fi

          # Commit and push changes
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update tBTC v2 contracts documentation"
            git push origin main
          fi
