name: NPM TBTCv2 Contracts

on:
  push:
    branches:
      - main
    paths:
      - "solidity/contracts/**"
      - "solidity/deploy/**"
      - "solidity/tasks/**"
      - "solidity/hardhat.config.ts"
      - "solidity/package.json"
      - "solidity/yarn.lock"
  workflow_dispatch:

jobs:
  npm-compile-publish-contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./solidity
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: solidity/yarn.lock

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate

      - name: Resolve latest contracts
        run: |
          yarn up --exact \
            '@keep-network/ecdsa@development' \
            '@keep-network/random-beacon@development'

      # Deploy contracts to a local network to generate deployment artifacts that
      # are required by dashboard compilation.
      - name: Deploy contracts
        run: yarn deploy:test --network hardhat --write true

      - name: Bump up package version
        id: npm-version-bump
        uses: threshold-network/ci/actions/npm-version-bump@20b35345d276a3c7365e3829b8078387a7c9dccb
        with:
          work-dir: ./solidity
          environment: dev
          branch: ${{ github.ref }}
          commit: ${{ github.sha }}

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access=public --tag=development --network=hardhat
