import { ethers } from "ethers"
import { artifacts } from "hardhat"
import { writeFile } from "fs/promises"

/**
 * Reservation ABI surface snapshot fixture.
 *
 * This snapshot must be regenerated by whichever future PR intentionally
 * changes the reservation ABI surface. A CI failure here means that PR
 * unexpectedly touched the reservation ABI surface consumed by keep-core's
 * client. A matching artifact SHOULD exist on the keep-core side for full
 * cross-repo protection; wiring CI to compare both snapshots is tracked
 * separately and out of scope here.
 */
export type FunctionSelectorInfo = {
  name: string
  selector: string
  inputs: string[]
  outputs: string[]
}

export type EventTopicInfo = {
  name: string
  topic0: string
  inputs: string[]
}

export type StructFieldInfo = { name: string; type: string }[]

export type ReservationAbiSnapshot = {
  functions: FunctionSelectorInfo[]
  events: EventTopicInfo[]
  structs: Record<string, StructFieldInfo>
}

type AbiParameter = { type: string; name?: string; components?: AbiParameter[] }
type AbiFragment =
  | {
      type: "function"
      name: string
      inputs: AbiParameter[]
      outputs: AbiParameter[]
    }
  | { type: "event"; name: string; inputs: AbiParameter[] }
  | { type: "constructor"; inputs: AbiParameter[] }
  | { type: "fallback"; stateMutability: string }
  | { type: "receive"; stateMutability: string }

async function getContractAbi(contractName: string): Promise<AbiFragment[]> {
  const artifact = await artifacts.readArtifact(contractName)
  return artifact.abi
}

/**
 * Compute the 4-byte selector for a function fragment.
 */
function getSelector(func: Extract<AbiFragment, { type: "function" }>): string {
  const signature = `${func.name}(${func.inputs.map((i) => i.type).join(",")})`
  return ethers.utils.id(signature).slice(0, 10)
}

/**
 * Extract struct field name/type pairs from a tuple-typed parameter (input or output) of a function.
 */
function getStructFields(
  abi: AbiFragment[],
  contractName: string,
  functionName: string,
  paramType: "input" | "output",
  paramIndex: number
): StructFieldInfo {
  const func = abi.find(
    (f): f is Extract<AbiFragment, { type: "function" }> =>
      f.type === "function" && f.name === functionName
  )
  if (!func) {
    throw new Error(
      `Function ${functionName} not found in ABI of ${contractName}`
    )
  }
  const paramArray = paramType === "input" ? func.inputs : func.outputs
  if (!paramArray || paramIndex >= paramArray.length) {
    throw new Error(
      `Parameter index ${paramIndex} out of bounds for ${functionName} in ${contractName}`
    )
  }
  const param = paramArray[paramIndex]
  if (param.type !== "tuple") {
    throw new Error(`Parameter ${paramIndex} of ${functionName} is not a tuple`)
  }
  if (!param.components) {
    throw new Error(
      `Tuple parameter ${paramIndex} of ${functionName} has no components`
    )
  }
  return param.components.map((c) => ({ name: c.name ?? "", type: c.type }))
}

export async function getReservationAbiSnapshot(): Promise<ReservationAbiSnapshot> {
  // Read the artifacts
  const bridgeAbi = await getContractAbi("IReservationBridge")
  const validatorAbi = await getContractAbi("WalletProposalValidator")

  // Collect functions: all from IReservationBridge and the two validator entry points
  const bridgeFunctions = bridgeAbi
    .filter(
      (f): f is Extract<AbiFragment, { type: "function" }> =>
        f.type === "function"
    )
    .map((f) => ({
      name: f.name,
      selector: getSelector(f),
      inputs: f.inputs.map((i) => i.type),
      outputs: f.outputs.map((o) => o.type),
    }))

  const validatorFunctions = [
    "validateReservationAnchorProposal",
    "validateReservationReanchorProposal",
  ].map((name) => {
    const fn = validatorAbi.find(
      (candidate): candidate is Extract<AbiFragment, { type: "function" }> =>
        candidate.type === "function" && candidate.name === name
    )
    if (!fn) {
      throw new Error(
        `Function ${name} not found in WalletProposalValidator ABI`
      )
    }
    return {
      name: fn.name,
      selector: getSelector(fn),
      inputs: fn.inputs.map((i) => i.type),
      outputs: fn.outputs.map((o) => o.type),
    }
  })

  const functions = [...bridgeFunctions, ...validatorFunctions]

  // Collect events: all from IReservationBridge
  const events = bridgeAbi
    .filter(
      (e): e is Extract<AbiFragment, { type: "event" }> => e.type === "event"
    )
    .map((e) => ({
      name: e.name,
      topic0: ethers.utils.id(
        `${e.name}(${e.inputs.map((i) => i.type).join(",")})`
      ),
      inputs: e.inputs.map((i) => i.type),
    }))

  // Collect structs from the relevant functions
  const structs: ReservationAbiSnapshot["structs"] = {
    ReservationRequest: getStructFields(
      bridgeAbi,
      "IReservationBridge",
      "reservations",
      "output",
      0
    ),
    ReservationAction: getStructFields(
      bridgeAbi,
      "IReservationBridge",
      "reservationActions",
      "output",
      0
    ),
    ReservationAnchorProposal: getStructFields(
      validatorAbi,
      "WalletProposalValidator",
      "validateReservationAnchorProposal",
      "input",
      0
    ),
    ReservationReanchorProposal: getStructFields(
      validatorAbi,
      "WalletProposalValidator",
      "validateReservationReanchorProposal",
      "input",
      0
    ),
  }

  return { functions, events, structs }
}

export async function writeReservationAbiSnapshot(
  snapshot: ReservationAbiSnapshot,
  outputPath: string
): Promise<void> {
  const content = JSON.stringify(snapshot, null, 2)
  await writeFile(outputPath, content, "utf8")
}
